language: python
python:
- "3.7"
-
install:
#install conda
 - sudo apt-get update
 - sudo apt-get -y upgrade
 - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
 - bash miniconda.sh -b -p $HOME/miniconda
 - source "$HOME/miniconda/etc/profile.d/conda.sh"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda

 - conda info -a

 - ./env.sh


script:
 - python -m unittest discover
