# Anaconda YAML file specifying packages that this project's build/test
# environment should install from Anaconda's "conda-forge" channel.
channels:
  - defaults
  - conda-forge
dependencies:
 - spacy
 - pyarrow
 - fastparquet 
 - plotly
 - ipywidgets


