# Anaconda YAML file specifying packages that this project's build/test
# environment should install from Anaconda's main channel.
channels:
  - defaults
dependencies:
 - tensorflow
 - pandas
 - regex
 - matplotlib
 - cython 
 - grpcio-tools
 - pytorch
 - black
 - scikit-learn 


